### ISSUE TITLE
Manager change password form in manager settings

### ISSUE THREAD

**Issue by Grommash9** [Grommash9/tg_chat_mate#130]
Managers should be able to change their passwords from UI

blocked by #128

**Comment by saisreesatyassss** [comment]
i would like to work on this repo where can i know how to install it locally and to discuss the issues

**Comment by Grommash9** [comment]
Hello, my friend, there is some information on docs page

https://grommash9.github.io/tg_chat_mate/

Also we have a group chat in telegram and you are welcome to join it

https://t.me/tg_chat_mate_contributors

There we can help you and answer any questions 

We are only starting these project so docs can looks not great, but I am happy to add any info what missing
