### ISSUE TITLE
Run python and typescript code check pipelines in parallel

### ISSUE THREAD

**Issue by Grommash9** [Grommash9/tg_chat_mate#169]
https://docs.travis-ci.com/user/build-stages/

We can see it's possible to run some stages or scripts in parallel and it can we very useful for us to do it these way.

In future we will add tests for python code, and I hope we will be able to add some TS tests, so there will be more things what we will want to use in parallel

Acceptance criteria:

1. python and ts code check pipelines are running in parallel

**Comment by Jonatan-Chaverri** [comment]
Not sure what you mean. I see that both stages are being run in parallel right now.
<img width="503" alt="Screenshot 2024-01-16 at 17 43 13" src="https://github.com/Grommash9/tg_chat_mate/assets/25421284/cefc37fb-be0d-4f3f-915b-56ff3adc8888">

According to the official Travis documentation

> Stages group jobs that run in parallel and different stages run sequentially.

So to run jobs in parallel, you just need them to be in the same stage which is already the case for _Python linting_ and _Typescript linting_  jobs.

**Comment by Grommash9** [comment]
On Travis website we can see how it's run not in parallel, but one by one

Also we can see it looking at time consumed by first stage

It should be 1 min 58 sec if it runs in parallel 

![image](https://github.com/Grommash9/tg_chat_mate/assets/67575598/8a555981-9e03-48a6-8846-87c2037c96c6)

**Comment by Jonatan-Chaverri** [comment]
@Grommash9 which Travis plan are you using? I can see that **bootstrap** plan only allow **one concurrent job** at the time, hence no parallelism is allowed. 
https://www.travis-ci.com/pricing-cloud/

**Comment by Grommash9** [comment]
Oh, yes, true, we are using minimal one now, yes that's why it's not working as expected. Thanks for figuring it out.
