### ISSUE TITLE
Python testing should be done before deploying

### ISSUE THREAD

**Issue by Jonatan-Chaverri** [Grommash9/tg_chat_mate#173]
Python tests should run before deploying the bot image, in that way we can prevent breaking test environment.

While testing against the real live project can provide feedback in real time, it is also time consuming and makes it hard to add new tests that requires data in the db. 

I propose the following changes
- Move the tests stage before deploy stage.
- Use Python mock library to be able to test the code without having an actual image of the code running. This will save a lot of the time by just testing the logic of the code and not external data like data in db, or external API calls, among other external things.
- Use coverage library to test PRs coverage. Any code that's been merge should have unittest. In this way we can assure that and fail under 80% coverage. (optional)

**Comment by Grommash9** [comment]
Yes, we should have it for sure. 

I like post deploy tests because it can help me to understand our services are working fine together, like redis and mongo db are accessible from both

But you are totally right what we need mocking and covering and tests before deploy stage

Also i want to mention it's not real deploy, is our test server and the logic of it is to check nginx config working fine and code is ready to be deployed to customers, we are uninstalling it after deploy, so maybe we should rename these stage it future to prevent confusion

**Comment by Grommash9** [comment]
So i think we should add right tests for sure with mocking but at same time I am not sure i want remove all post deploy tests, I like it really and I think they are able to test more different things and make us sure all is working fine

It's like QA automation if we can say it

Maybe we also should rename it somehow

**Comment by Jonatan-Chaverri** [comment]
You are right, its valuable to have those tests also. 

Maybe what we can do is have like a separate job running periodically against the test environment with those post deploy tests. Not sure if travis have that capability.

But for PRs, my opinion is that we should not run them, because they take a lot of time to complete and when the app starts to grow it will get worse. For PRs only unittest should be running.

I can take care of creating those unit test. Will try to hit at least 80% of the code. But let me know if you agree before start working on this that potentially can take some time.

**Comment by Grommash9** [comment]
Yes, i want to have it for sure.

I am not sure now about removing post deploy test part to be honest, but i will think how to speed it up, have some ideas

**Comment by Grommash9** [comment]
Was closed in

https://github.com/Grommash9/tg_chat_mate/pull/175
