### ISSUE TITLE
Endpoint for Ban users

### ISSUE THREAD

**Issue by Grommash9** [Grommash9/tg_chat_mate#80]
We should have endpoint in tg bot to ban users, after ban user will still be able to send messages but we will not save them into database and will not notify anybody about it

**Comment by lifquti** [comment]
in this case you mean add endpoint, create in db banned list and add new filter for banned id?

**Comment by Grommash9** [comment]
I think we can just add the field for user, because mongoDB allow us to have users without'banned' field on user creation, and we can add it later. 

Also now i understood we also want to be able to unban them. So endpoint should use 'user_id' and new banned boolean as True or False and we should add these field or update 


So we will have 3 states
- User don't have banned field (he is not banned)
- user have banned field with False in it (he is not banned)
- user have banned field with True (banned)

Also as you mentioned we want to have a filer to just skip all updates from banned users.

**Comment by Grommash9** [comment]
It should use auth decorator like other api's and return error if we can find the user
